spring:
      datasource:
            url: jdbc:postgresql://localhost:5432/demodb
            username: postgres
            password: 1234
      jpa:
            show-sql: true
            properties:
                  hibernate.format_sql: true



    