spring:
      output:
            ansi:
                  enabled: ALWAYS
      datasource:
            url: jdbc:postgresql://localhost:5432/demodb
            username: postgres
            password: 1234
      jpa:
            show-sql: true
            open-in-view: false
            generate-ddl: false
            properties:
                  hibernate.format_sql: true




    